import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { Bot, MessageCircle, Minus, Send, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { authorities } from "../../data/authorities";
import { useStore } from "../../store/DemoStore";
import { getLocalResponse, getResponse, welcome } from "./chatbotService";
import type { ChatAction, ChatMessage, FormBridge } from "./types";

type ChatValue={open:()=>void;improveDraft:()=>void;setFormBridge:(bridge:FormBridge|undefined)=>void};const ChatContext=createContext<ChatValue|null>(null);const key="rti-online-demo/chat-v1";const quick=["How do I file an RTI?","Help me choose an authority","Improve my RTI request","Track my application","Help with a first appeal"];const id=()=>`${Date.now()}-${Math.random().toString(36).slice(2,7)}`;const nil={open:()=>undefined,improveDraft:()=>undefined,setFormBridge:()=>undefined};export const useChatbot=()=>useContext(ChatContext)??nil;
function read(){try{const stored=localStorage.getItem(key);const parsed=stored?JSON.parse(stored):[];return Array.isArray(parsed)?parsed:[]}catch{return[]}}
export function ChatbotProvider({children}:{children:ReactNode}){const{applications}=useStore();const nav=useNavigate();const[shown,setShown]=useState(false),[minimized,setMinimized]=useState(false),[input,setInput]=useState(""),[bridge,setBridge]=useState<FormBridge>(),[messages,setMessages]=useState<ChatMessage[]>(read),[loading,setLoading]=useState(false);const inputRef=useRef<HTMLInputElement>(null),scrollRef=useRef<HTMLDivElement>(null);
useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(messages.slice(-30)))}catch{}},[messages]);useEffect(()=>{if(shown&&!minimized)inputRef.current?.focus()},[shown,minimized]);useEffect(()=>{scrollRef.current?.scrollTo({top:scrollRef.current.scrollHeight,behavior:"smooth"})},[messages,loading]);useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setShown(false)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
const open=useCallback(()=>{setShown(true);setMinimized(false);if(!messages.length)setMessages([{id:id(),role:"assistant",content:welcome,timestamp:Date.now()}])},[messages.length]);const improveDraft=useCallback(()=>{open();if(!bridge?.request)return;const r=getResponse("improve my RTI request",bridge,applications);setMessages(old=>[...old,{id:id(),role:"assistant",...r,timestamp:Date.now()}])},[applications,bridge,open]);
const send=async(raw=input)=>{const message=raw.trim().slice(0,1200);if(!message||loading)return;const history=messages.slice(-12).map(({role,content})=>({role,content}));setInput("");setMessages(old=>[...old,{id:id(),role:"user",content:message,timestamp:Date.now()}]);const local=getLocalResponse(message,bridge,applications);if(local){setMessages(old=>[...old,{id:id(),role:"assistant",content:local.content,kind:local.kind,actions:local.actions,timestamp:Date.now()}]);if(local.authorities?.length)setMessages(old=>[...old,...local.authorities.map(a=>({id:id(),role:"assistant" as const,content:`${a.name}\n${a.category} · ${a.description}`,actions:[{label:`Select ${a.name}`,kind:"select_authority" as const,value:a.id}],timestamp:Date.now()}))]);return}setLoading(true);try{const response=await fetch("/api/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message,conversationHistory:history,context:{currentPage:window.location.pathname,selectedAuthority:bridge?.authority?.name}})});const body=await response.json().catch(()=>({}));if(!response.ok||typeof body.content!=="string")throw Error();setMessages(old=>[...old,{id:id(),role:"assistant",content:body.content,timestamp:Date.now()}])}catch{setMessages(old=>[...old,{id:id(),role:"assistant",content:"I'm sorry, I'm unable to answer that right now. Please try again in a moment.",timestamp:Date.now()}])}finally{setLoading(false)}};
const action=(a:ChatAction)=>{if(a.kind==="navigate"&&typeof a.value==="string")nav(a.value);if(a.kind==="select_authority"){const found=authorities.find(x=>x.id===a.value);if(found&&bridge?.selectAuthority){bridge.selectAuthority(found);setMessages(old=>[...old,{id:id(),role:"assistant",content:`${found.name} has been selected in your form. Please confirm it is the right authority before continuing.`}])}}if(a.kind==="use_suggestion"&&typeof a.value==="string"&&bridge?.useSuggestion){bridge.useSuggestion(a.value);setMessages(old=>[...old,{id:id(),role:"assistant",content:"The suggested wording has been placed in your draft. Please review and edit it before continuing."}])}};const value=useMemo(()=>({open,improveDraft,setFormBridge:setBridge}),[open,improveDraft]);
return <ChatContext.Provider value={value}>{children}<button className="chat-launcher" onClick={open} aria-label="Ask RTI Assistant" title="Ask RTI Assistant"><MessageCircle size={20}/><span>RTI Assistant</span></button>{shown&&!minimized&&<section className="chat-window" aria-label="RTI Assistant"><header className="chat-head"><Bot size={19}/><div><b>RTI Assistant</b><small>Guidance for filing and tracking your RTI</small></div><button onClick={()=>setMinimized(true)} aria-label="Minimize assistant"><Minus size={17}/></button><button onClick={()=>setShown(false)} aria-label="Close assistant"><X size={17}/></button></header><div className="chat-context">Online · Portal guidance and demo data</div><div className="chat-messages" ref={scrollRef} aria-live="polite">{messages.map(m=><article className={`chat-message ${m.role} ${m.kind??""}`} key={m.id}>{m.content.split("\n").map((line,i)=><p key={i}>{line||" "}</p>)}{m.actions?.map(a=><button key={a.label} onClick={()=>action(a)}>{a.label}</button>)}</article>)}{loading&&<p className="chat-typing">RTI Assistant is typing<span>…</span></p>}{messages.length<=1&&<div className="chat-quick">{quick.map(item=><button key={item} onClick={()=>send(item)} disabled={loading}>{item}</button>)}</div>}<p className="chat-disclaimer">This assistant provides general guidance for using this portal and should not be treated as official legal advice.</p></div><form className="chat-input" onSubmit={e=>{e.preventDefault();send()}}><input ref={inputRef} value={input} maxLength={1200} disabled={loading} onChange={e=>setInput(e.target.value)} placeholder="Ask about your RTI" aria-label="Message RTI Assistant"/><button aria-label="Send message" disabled={loading||!input.trim()}><Send size={17}/></button></form></section>}{shown&&minimized&&<button className="chat-minimized" onClick={()=>setMinimized(false)}>Continue your RTI guidance</button>}</ChatContext.Provider>}
